### ISSUE TITLE
Invalid redirect

### ISSUE THREAD

**Issue by rav1k** [Vertco/DataverseForNinjaOne#2]
Is this still maintained? I'm getting an invalid redirect when attempting to test along with the error message: 
{ "resultCode": "FAILURE", "errorMessage": "HTTP 404 Not Found", "incidentId": "WEB_MGMT_SERVICE-2a-1706726772-HMIZOFZF" }

I'm located in the US so i've changes the urls to app.ninjarmm.com

**Comment by NixXxn** [comment]
Same issue (eu instance). I think it is no maintaned anymore.... Would be great if someone would fork and update it. :)

**Comment by NixXxn** [comment]
I managed it. I think it has something todo with the redirect URL. See screenshots of my configuration below (which works). In your case the url should be app.ninjarmm.com instead of eu.ninjarmm.com and make sure you copy / paste the redirect url from Ninja.
![image](https://github.com/Vertco/DataverseForNinjaOne/assets/11144751/f6fe5eb0-53a4-420e-8c93-0d7a57887800)
![image](https://github.com/Vertco/DataverseForNinjaOne/assets/11144751/bec2cad5-7eb6-44c3-82e2-861bd9cdda1a)
Redirect URL must match the redirect URL from Ninja:
![image](https://github.com/Vertco/DataverseForNinjaOne/assets/11144751/7a64bdba-6087-4c8c-9174-6fc8312ee655)

**Comment by rav1k** [comment]
Interesting, I don't think I'm comprehending the redirect link portion correctly. Below is my exact error when attempting to use the connection along with the connector settings and the ninja api settings. If I'm following this correctly, I should be taking the auto generated redirect URL from the power automate connector and pasting it into the NinjaOne API app ID?  I've also tried making the NinjaOne app id in two formats using the API Machine to Machine key and the web version as well.
![image](https://github.com/Vertco/DataverseForNinjaOne/assets/73625904/aeda8a7c-f1d6-4457-9502-a0f1bae609d7)

Here I've taken the redirect URL.
![image](https://github.com/Vertco/DataverseForNinjaOne/assets/73625904/6b4ffdc3-b092-4057-82a9-4a05dfc473f1)


And pasted it into the app id

![image](https://github.com/Vertco/DataverseForNinjaOne/assets/73625904/3efb5f5f-33bc-4df5-a6d4-690d13d88ac8)

**Comment by NixXxn** [comment]
Your settings look good actually. - I had exactly the same error at first. Then I recreated the machine-to-machine key, generated a new secret and added the connector complety new and it was working just fine.

Does your the first page look like:
![image](https://github.com/Vertco/DataverseForNinjaOne/assets/11144751/aee3daaf-2241-4825-b782-e71efdf9984a)

?

You can also try this .json file. I changed the urls directly in the file.
[DataverseForNinjaOne.swagger.json](https://github.com/Vertco/DataverseForNinjaOne/files/14450092/DataverseForNinjaOne.swagger.json)

**Comment by rav1k** [comment]
Yeah my first screen looks just like yours minus the eu.
I tried the json file as well and still the same issue. Wonder if it's a US thing or a tenant restriction of some sort.

**Comment by NixXxn** [comment]
I've just tried with app.ninjarmm.com and it works.

You just need to follow these step.
1. Create API in Ninja (Write down the Secret + ClientID)
2. Create Custom Connector in PowerApps (Save the connector --> An error will appear, ignore it)
3. Edit your API key in Ninja and paste the redirect URL from your connector.
4. Go back to the connetor and save it again --> This time no error will appear.

Thats how I did it. Also with US instance.

**Comment by rav1k** [comment]
> I've just tried with app.ninjarmm.com and it works.
> 
> You just need to follow these step.
> 
> 1. Create API in Ninja (Write down the Secret + ClientID)
> 2. Create Custom Connector in PowerApps (Save the connector --> An error will appear, ignore it)
> 3. Edit your API key in Ninja and paste the redirect URL from your connector.
> 4. Go back to the connetor and save it again --> This time no error will appear.
> 
> Thats how I did it. Also with US instance.

It works thanks!
I just added the /v2/ticketing/ticket endpoint to it and verified that works as well.

**Comment by TargetCrafter** [comment]
For some reason GitHub didn't notify me about this issue, but I'll see if i can update the repo to the latest Ninja release so that it supports the latest endpoints.
